full_name = input("Adınız ve Soyadınız: ")
student_id = input("Öğrenci Numaranız: ")
major = input("Bölümünüz: ")
favorite_language = input("En Sevdiğiniz Programlama Dili: ")
graduation_year = input("Hedef Mezuniyet Yılınız: ")
print("\n========================================")
print("       ÖĞRENCİ TANITIM KARTI            ")
print("========================================")
print(f"Ad Soyad       : {full_name}")
print(f"Öğrenci No     : {student_id}")
print(f"Bölüm          : {major}")
print(f"Favori Dili    : {favorite_language}")
print(f"Mezuniyet Yılı : {graduation_year}")
print("========================================\n")
